import 'models/ocr_language.dart';

class LanguageRegistry {
  const LanguageRegistry._();

  static const List<OcrLanguage> languages = <OcrLanguage>[
    OcrLanguage(
      displayName: 'Arabic',
      code: 'ara',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'ara',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Bengali',
      code: 'ben',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'ben',
      bundled: true,
    ),
    OcrLanguage(
      displayName: 'Bengali+English',
      code: 'ben_eng',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'ben+eng',
      bundled: true,
    ),
    OcrLanguage(
      displayName: 'Burmese',
      code: 'mya',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'mya',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Chinese (Simplified)',
      code: 'chi_sim',
      engine: OcrEngine.mlkit,
      mlkitScript: 'chinese',
      mlkitNeedsDownload: true,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Chinese (Traditional)',
      code: 'chi_tra',
      engine: OcrEngine.mlkit,
      mlkitScript: 'chinese',
      mlkitNeedsDownload: true,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'English',
      code: 'eng',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: true,
    ),
    OcrLanguage(
      displayName: 'French',
      code: 'fra',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'German',
      code: 'deu',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Gujarati',
      code: 'guj',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'guj',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Hindi',
      code: 'hin',
      engine: OcrEngine.mlkit,
      mlkitScript: 'devanagari',
      mlkitNeedsDownload: true,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Italian',
      code: 'ita',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Japanese',
      code: 'jpn',
      engine: OcrEngine.mlkit,
      mlkitScript: 'japanese',
      mlkitNeedsDownload: true,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Kannada',
      code: 'kan',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'kan',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Korean',
      code: 'kor',
      engine: OcrEngine.mlkit,
      mlkitScript: 'korean',
      mlkitNeedsDownload: true,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Malayalam',
      code: 'mal',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'mal',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Marathi',
      code: 'mar',
      engine: OcrEngine.mlkit,
      mlkitScript: 'devanagari',
      mlkitNeedsDownload: true,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Portuguese',
      code: 'por',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Punjabi',
      code: 'pan',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'pan',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Russian',
      code: 'rus',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Spanish',
      code: 'spa',
      engine: OcrEngine.mlkit,
      mlkitScript: 'latin',
      mlkitNeedsDownload: false,
      tessCode: null,
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Tamil',
      code: 'tam',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'tam',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Telugu',
      code: 'tel',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'tel',
      bundled: false,
    ),
    OcrLanguage(
      displayName: 'Thai',
      code: 'tha',
      engine: OcrEngine.tesseract,
      mlkitScript: null,
      mlkitNeedsDownload: false,
      tessCode: 'tha',
      bundled: false,
    ),
  ];

  static OcrLanguage byCode(String code) {
    return languages.firstWhere(
      (OcrLanguage language) => language.code == code,
      orElse: () => languages.firstWhere(
        (OcrLanguage language) => language.code == 'ben',
      ),
    );
  }
}
